dataset_root : 'D:\python\pycharm\pytorchlearn\LIF-FreqNet\LIF-FreqNet\MSRS-main\MSRS-main'
dataset_name : MSRS
seed : 3407
have_seg_label : False
project_name : LIF-FreqNet
exp_name : model-1_1_10_1
resume : ~
img_size : 320
log_level : INFO
wandb_mode: offline
start_epoch : 0
num_epochs : 50
epoch_gap : 50
batch_size : 4
num_workers : 2
lr_i : 0.001
lr_f : 0.1
momentum : 0.937
coeff_content: 1
coeff_ssim: 1
coeff_saliency: 10
coeff_fre: 2


